name: "Prueba de Action"

on:
    #push:
        #branches: [main,develop]
    workflow_dispatch:
        inputs: 
            entorno:
                required: true
                default: 'dev'
                type: choice
                options: 
                    - dev
                    - prod
                    - qa

jobs:
    test-action-job:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        environment: ${{ github.event.inputs.entorno || 'dev' }}


        steps:
            - name: Ejecutar el Action
              uses: tareas-dani/t1action@main
              id: actiontarea
              with:
                nombre: ${{ vars.NOMBRE }}
                edad: ${{ vars.EDAD }}
        
            - name: Imprimir el resultado del Action
              run: |
                echo "Multiplicacion es: ${{ steps.actiontarea.outputs.multiplicacion }}"
    
    llamado-reusable-workflow:
        uses: tareas-dani/reusable-workflows/.github/workflows/hola.yml@main
        with:
            nombre: 'Daniela'
