name: "Prueba de Action"

on:
    push:
        branches: [release]
    workflow_dispatch:

jobs:
    test-action:
        runs-on: ubuntu-latest
        environment: ${{ github.ref_name == 'develop' && 'dev' || github.ref_name == 'main' && 'prod' || github.ref_name == 'release' && 'qa' }}
        permissions:
            contents: read

        steps:
            - name: Ejecutar el Action
              uses: tareas-dani/t1action@main
              with:
                nombre: daniela
                edad: 10
