name: "Prueba de Action"

on:
    #push:
        #branches: [main,develop]
        workflow_dispatch:
            inputs: 
                entorno:
                    required: true
                    default: 'dev'
                    type: choice
                    options: 
                        - dev
                        - prod
                        - qa

jobs:
    test-action-job:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Ejecutar el Action
              uses: tareas-dani/t1action@main
              with:
                nombre: ${{ vars.NOMBRE }}
                edad: 20
    
    llamado-reusable-workflow:
        uses: tareas-dani/reusable-workflows/.github/workflows/hola.yml@main
        with:
            nombre: 'Daniela'